name: Gothub ERP - Unit Test Pipeline

# 1. Kapan robot ini harus bekerja?
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

# 2. Apa tugas utamanya?
jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest # Menggunakan server Linux gratis dari GitHub

    steps:
    # Langkah A: Mengambil kode dari repositorimu
    - name: 📥 Checkout Repository
      uses: actions/checkout@v4

    # Langkah B: Memasang bahasa Go versi 1.26
    - name: ⚙️ Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.26'
        cache: true # Mempercepat proses build selanjutnya

    # Langkah C: Mengunduh semua library (seperti Gin dan GORM)
    - name: 📦 Download Dependencies
      run: go mod download

    # Langkah D: Menjalankan semua Unit Test yang ada di proyek
    - name: 🧪 Run Unit Tests
      # Perintah ./... artinya mencari semua file test di dalam folder dan subfolder
      run: go test -v ./...